#url: http://economicsofmalaria.com/
# baseurl: /joebrew.github.io/

# Site settings
title: Goldenberg Lab
email: benmbrew@gmail.com
description: "Using Machine Learing to Solve Problems in Computational Biology"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2980B9
  secondary: 9A9E9E  
  secondary-dark: 333

main:

- name: Anna Goldenberg
  pic: 1_anna
  position: Professor of Machine Learing
  social:
    - title: linkedin
      url: #http://github.com/joebrew   
    - title: github
      url: #https://www.linkedin.com/in/joe-brew-1061a33a
    - title: twitter
      url: #https://twitter.com/bcndata

people:


- name: Anna Goldenberg
  pic: 1_resized
  position: Scientist at SickKids Assistant Professor at U of T
  social:
    - title: linkedin
      url: #http://github.com/joebrew   
    - title: github
      url: #https://www.linkedin.com/in/joe-brew-1061a33a
    - title: twitter
      url: #https://twitter.com/bcndata

- name: Aziz Mezilini
  pic: 2_resized
  position: Phd Researcher
  social:
    - title: linkedin
      url: #http://github.com/joebrew   
    - title: github
      url: #https://www.linkedin.com/in/joe-brew-1061a33a
    - title: twitter
      url: #https://twitter.com/bcndata

- name: Ladislav Rampasek
  pic: 3_resized
  position: Phd Researcher
  social:
    - title: linkedin
      url: #https://es.linkedin.com/in/elisa-sicuri-02821217
    - title: github
      url: #http://www.imperial.ac.uk/people/e.sicuri
    - title: twitter
      url: #https://www.facebook.com/elisa.sicuri

- name: Lauren Erdman
  pic: 4_resized
  position: Graduate Researcher
  social:
    - title: linkedin
      url: #https://www.linkedin.com/in/laia-cirera-i-crivillé-53476316
    - title: github
      url: #https://www.upf.edu/cres/en/membres/colaboradors/cirera_laia.html
    - title: twitter
      url: #https://www.facebook.com/laia.cirera

- name: Daniel Hirdu
  pic: 5_resized
  position: Graduate Researcher
  social:
    - title: linkedin
      url: #https://nl.linkedin.com/in/menno-pradhan-74506b54
    - title: github
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx
    - title: twitter
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx

- name: Shems Saleh
  pic: 10_resized
  position: Graduate Researcher
  social:
    - title: linkedin
      url: #https://nl.linkedin.com/in/menno-pradhan-74506b54
    - title: github
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx
    - title: twitter
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx

- name: Ben Brew
  pic: 8_resized
  position: Programmer/Analyst
  social:
    - title: linkedin
      url: #https://nl.linkedin.com/in/menno-pradhan-74506b54
    - title: github
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx
    - title: twitter
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx


- name: Tal Friedman
  pic: 6_resized
  position: Undergraduate Researcher
  social:
    - title: linkedin
      url: #https://nl.linkedin.com/in/menno-pradhan-74506b54
    - title: github
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx
    - title: twitter
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx

- name: Ekansh Sharma
  pic: 7_resized
  position: Undergraduate Researcher
  social:
    - title: linkedin
      url: #https://nl.linkedin.com/in/menno-pradhan-74506b54
    - title: github
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx
    - title: twitter
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx

- name: Dustin
  pic: 9_resized
  position: Undergraduate Researcher
  social:
    - title: linkedin
      url: #https://nl.linkedin.com/in/menno-pradhan-74506b54
    - title: github
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx
    - title: twitter
      url: #http://www.feweb.vu.nl/en/departments-and-institutes/development-economics/staff/m-pradhan/index.aspx

address:
  - line: Peter Gilgan Centre for Research and Learning
  - line: 686 Bay St, Toronto, ON M5G 0A4

# Build settings
markdown: kramdown
permalink: pretty